import { Repository } from '../types';

export const MOCK_REPOS: Array<Repository> = [
  {
    uniqueName: 'facebook/react',
    name: 'react',
    stars: 155165,
    watchers: 6690,
    forks: 6690,
    url: 'https://github.com/facebook/react',
    description:
      'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    topics: ['javascript', 'react', 'frontend', 'declarative', 'ui', 'library'],
  },
  {
    uniqueName: 'typescript-cheatsheets/react',
    name: 'react',
    stars: 16882,
    watchers: 248,
    url: 'https://github.com/typescript-cheatsheets/react',
    forks: 6690,
    description:
      'Cheatsheets for experienced React developers getting started with TypeScript',
    topics: [],
  },
  {
    uniqueName: 'duxianwei520/react',
    name: 'react',
    stars: 3839,
    watchers: 190,
    url: 'https://github.com/duxianwei520/react',
    forks: 6690,
    description: ' React+webpack+redux+ant design+axios+less全家桶后台管理框架',
    topics: [
      'react',
      'webpack',
      'antd',
      'es6',
      'redux',
      'babel',
      'es7',
      'ant-design-pro',
    ],
  },
  {
    uniqueName: 'discountry/react',
    name: 'react',
    stars: 964,
    watchers: 39,
    url: 'https://github.com/discountry/react',
    forks: 6690,
    description: 'React docs in Chinese | React 中文文档翻译',
    topics: ['react', 'docs'],
  },
  {
    uniqueName: 'Cathy0807/react',
    name: 'react',
    stars: 672,
    watchers: 41,
    forks: 6690,
    url: 'https://github.com/Cathy0807/react',
    description: '京东首页构建',
    topics: [],
  },
  {
    uniqueName: 'react-redux-antd-es6/react',
    forks: 6690,
    name: 'react',
    stars: 737,
    watchers: 47,
    url: 'https://github.com/react-redux-antd-es6/react',
    description: '基于react的企业后台管理开发框架',
    topics: ['react', 'antd', 'webpack'],
  },
  {
    uniqueName: 'HackYourFuture/React',
    forks: 6690,
    name: 'React',
    stars: 94,
    watchers: 23,
    url: 'https://github.com/HackYourFuture/React',
    description:
      'This repository contains all the material for the HackYourFuture module "React.js: Building dynamic UIs with modern JavaScript"',
    topics: ['react', 'mobx', 'hyf'],
  },
  {
    uniqueName: 'ReactiveCocoa/ReactiveCocoa',
    forks: 6690,
    name: 'ReactiveCocoa',
    stars: 19859,
    watchers: 874,
    url: 'https://github.com/ReactiveCocoa/ReactiveCocoa',
    description:
      'Cocoa framework and Obj-C dynamism bindings for ReactiveSwift.',
    topics: ['reactiveswift', 'reactivecocoa', 'swift'],
  },
  {
    uniqueName: 'facebook/react-native',
    forks: 6690,
    name: 'react-native',
    stars: 89828,
    watchers: 3737,
    url: 'https://github.com/facebook/react-native',
    description: 'A framework for building native apps with React.',
    topics: [],
  },
  {
    uniqueName: 'geist-org/react',
    forks: 6690,
    name: 'react',
    stars: 987,
    watchers: 18,
    url: 'https://github.com/geist-org/react',
    description: 'Modern and minimalist React UI library.',
    topics: [
      'react-components',
      'react',
      'component',
      'geist',
      'design-system',
      'geist-ui',
    ],
  },
];
